name = "ben_mil"
version = "0.7.3"
defaultTargets = ["my_files"]

[[lean_lib]]
name = "my_files"
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
leanOptions = { linter.unusedVariables = false, weak.linter.unusedTactic = false }

[[lean_lib]]
name = "MIL"
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[lean_lib]]
name = "MIL_Solutions"
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[lean_lib]]
name = "Random"
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.16.0"
