name = "ben_mil"
version = "0.10.4"
defaultTargets = ["my_files"]
lintDriver = "Linter"

[[lean_lib]]
name = "my_files"
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
leanOptions = { linter.unusedVariables = false, weak.linter.unusedTactic = false, linter.missingDocs = false }

[[lean_lib]]
name = "Random"
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.20.0"

[[lean_exe]]
name = "Linter"
srcDir = "Random"
supportInterpreter = true
