name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build: "true"
          lint: "false"
          use-mathlib-cache: "true"
          
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build: "true"
          test: "false"
          lint: "true"
          use-mathlib-cache: "true"
