name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build: "true"
          test: "false"
          lint: "true"
          use-mathlib-cache: "true"
          lean4checker: "true"
          use-github-cache: "true"
